apiVersion: apps/v1
kind: Deployment
metadata:
  name: msv-pagos
spec:
  replicas: 2
  selector:
    matchLabels:
      app: msv-pagos
  template:
    metadata:
      labels:
        app: msv-pagos
    spec:
      containers:
        - name: msv-pagos
          image: johan1405/microservicio-pagos:latest
          ports:
            - containerPort: 8000
          envFrom:
            - configMapRef:
                name: msv-pagos-config
---
apiVersion: v1
kind: Service
metadata:
  name: msv-pagos-service
spec:
  type: LoadBalancer
  selector:
    app: msv-pagos
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
